all: clustershell_client clustershell_server shell

clustershell_client: clustershell_client.c
	gcc -o clustershell_client clustershell_client.c

clustershell_server: clustershell_server.c
	gcc -o clustershell_server clustershell_server.c

shell: shell.c
	gcc -o shell shell.c